### ISSUE TITLE
Bet365 nst token 

### ISSUE THREAD

**Issue by georgait** [HMaker/jsfuck-debugger#2]
I am trying to place a bet on bet365 but when I do post request it requires the nst token which is generated once web page refreshed. How can I make use of your script to retrieve the token?

**Comment by HMaker** [comment]
@georgait Well this repository is not related to bet365. Use [this issue](https://github.com/Chiang97912/bet365.com/issues/9) to talk about it.

**Comment by LonelyCodeCat** [comment]
Does anyone want to cooperate with bet365's automatic profit project?
